# Generated by Django 5.1.4 on 2024-12-29 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzamodel_options_pizzamodel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{,19}$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
