# Generated by Django 5.1.4 on 2024-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashopmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
